### ISSUE TITLE
Related Text (associated words) does not always work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/jscin#18]
```
There are several issues here.

1. The help messages said you have to press Shift+Number.
   However that does not work - actually we can't press Shift.

2. Some IMs (to be more specific, those without auto_compose) like
   注音 or 簡易 , fail to use it.
```

Original issue reported on code.google.com by `hun...@google.com` on 29 Jul 2014 at 4:02

**Comment by hungte** [comment]
1. "we can't press shift" is fixed.
2. auto_compose can use it now.

**Comment by hungte** [comment]
BTW, related fixes are:
- https://github.com/google/jscin/commit/b68ff9ac1581abe01f8679a2dab2b5dc7fbdfe4e
- https://github.com/google/jscin/commit/c04c9c42b32e6cb558387e12d2f8ce8dc0dc0cc3
- https://github.com/google/jscin/commit/8738845e1bafc2d40a45da76973084eaaee5b029
