### ISSUE TITLE
點選文字輸入區時，原有文字會被清空

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/jscin#21]
```
What steps will reproduce the problem?
1.在行列輸入模式，會導致點選網址列時，網址直接被清空，
以致於無法剪下網址。也會導致按Ctrl+C(複製)時，變成執行Ctr
l+X(剪下)的行為，不易編輯文字。

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `oliverre...@gmail.com` on 7 Jan 2015 at 3:21

**Comment by monzawu** [comment]
[0001-Fix-issue-21-text-cleared-accidentally-when-select-t.txt](https://github.com/google/jscin/files/3250183/0001-Fix-issue-21-text-cleared-accidentally-when-select-t.txt)

I have a potential fix, but since I don't really understand the ime flow, just upload it for the authors review.

**Comment by Marksusu** [comment]
> 

谢谢，
但是，
怎么用这个文本文件呢？

**Comment by Marksusu** [comment]
> [0001-Fix-issue-21-text-cleared-accidentally-when-select-t.txt](https://github.com/google/jscin/files/3250183/0001-Fix-issue-21-text-cleared-accidentally-when-select-t.txt)
> 
> I have a potential fix, but since I don't really understand the ime flow, just upload it for the authors review.

谢谢，
但是，
怎么用这个文本文件呢？

**Comment by hungte** [comment]
Should be fixed by https://github.com/google/jscin/pull/29

Wait for next release (0.25) that should have this fix.
