### ISSUE TITLE
會有更新到 manifest v3 的計畫嗎？

### ISSUE THREAD

**Issue by ancientsky** [google/jscin#28]
在chromebook非常依賴jscin來使用嘸蝦米輸入法，不過最近 chrome web store 一直出現 "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions." 的警示，應該是跟 jscin 仍使用 manifest v2有關，不知有沒有計畫更新到v3？

**Comment by hungte** [comment]
有的。 之前聽說 IME extension API 要被 deprecate 掉所以預計 enforce V3 前可能 extension 就要不見了所以沒動，不過看來 IME extension API 又會多活一陣子。
現在預計會改 Manifest V3。

**Comment by hungte** [comment]
更新：改下去發現工程非常巨大，因為沒有 background page 了。
Patches welcome.

**Comment by hungte** [comment]
最近會先推幾次昇版，主要是修正之前的一些問題，加上為轉移成 v3 作準備，包含清除與轉移部份資料。
實際 MV3 應該還要再幾個月，起碼等全部的人都轉到新版、完成資料轉移。
(MV3 因為不再接受background page 了，所以拿不到 MV2 在 localStorage 存的資料。 最近推的新版會慢慢把資料都從 localStorage 移往 V3 推的 chrome.storage)

**Comment by hungte** [comment]
現在最新的 code base 已經可以在 chromebook 上跑 manifest v3 了，不過還有不少問題，加上考慮資料轉移，離真的昇版還要一陣子。

**Comment by hungte** [comment]
2.91.2 已發佈，這版就是轉換到 v3 的中介版。等到大多使用者完成轉移後就可正式發佈 manifest v3 的版本了。

**Comment by ancientsky** [comment]
Thank hungte for all the great jobs. Still waiting for the manifest v3 version to be published on Chrome Web store.
